"""make nullable fields nullable for error rows

Revision ID: 47741bc972eb
Revises: 825f77fffe91
Create Date: 2026-08-02 18:15:16.504093

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47741bc972eb"
down_revision: Union[str, Sequence[str], None] = "825f77fffe91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "request_logs", "chosen_model", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "request_logs", "provider", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "request_logs", "input_tokens", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "request_logs", "output_tokens", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "request_logs", "provider_latency_ms", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "request_logs",
        "provider_latency_ms",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "request_logs", "output_tokens", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "request_logs", "input_tokens", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "request_logs", "provider", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "request_logs", "chosen_model", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
