"""add fallback_count to request_logs

Revision ID: 90a3d5207239
Revises: 47741bc972eb
Create Date: 2026-08-03 10:50:56.459693

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90a3d5207239"
down_revision: Union[str, Sequence[str], None] = "47741bc972eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "request_logs",
        sa.Column("fallback_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("request_logs", "fallback_count")
    # ### end Alembic commands ###
